export { default as axiosInstance } from "./axiosInstance";
export * from "./cloudinary";
export * from "./lessons.service";
export * from "./socket.service";
export * from "./students.service";
export * from "./teachers.service";
export * from "./notifications";
export * from "./support.service";
export { getMyPayments } from "./students.service";
export { getMyPayouts, requestPayout } from "./teachers.service";
